steps:
  - name: install drupal
    plugin: Drupal
    runInstall: true
    profileName: standard
    clearCaches: false
  - name: change file perms
    command: "chown www-data /var/www/html/core/sites/default/settings.php ; chown www-data /var/www/html/core/sites/default/files "
